name: pick_my_dish
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  dropdown_search: ^5.0.2
  provider: ^6.0.5
  image_picker: ^1.0.4
  http: ^1.1.0
  intl: ^0.18.1
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.3.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  http: ^1.1.0
  mocktail: ^1.0.0
  sqflite_common_ffi: ^2.2.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "assets/icon/icon.png"  # Your 1024x1024 icon
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
   - assets/logo/
   - assets/login/
   - assets/sideMenu/
   - assets/recipes/
   
  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/times.ttf
